In [1]:
import torch
import numpy as np

A tensor is a number, vector, matrix, or any n-dimensional array.

In [2]:
#Number
t1 = torch.tensor(4)
print(t1)
t1.shape

tensor(4)


torch.Size([])

In [3]:
t1.dtype

torch.int64

In [4]:
#Vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [5]:
#Matrix
t3 = torch.tensor([[5., 6], 
                   [7 , 8], 
                   [9, 10]])
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [6]:
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

Tensor Operation And Gradient(Autograd)

In [7]:
t5 = torch.tensor([[5., 6], 
                   [7 , 8]], requires_grad = True)
t6 = torch.tensor([[10., 2], 
                   [3 , 8]],requires_grad = True)

In [8]:
res = t5 * t6
res

tensor([[50., 12.],
        [21., 64.]], grad_fn=<MulBackward0>)

##### Note: RuntimeError: grad can be implicitly created only for scalar outputs (and not vector(arrays))
##### A tensor has to have a regular proper shape and each element should have the same datatype

In [10]:
res.backward()
print('dres/dt5:', t5.grad)
print('dres/dt6:', t6.grad)

RuntimeError: grad can be implicitly created only for scalar outputs

Note: x.grad means gradient of something with respect to x

## Tensor Function

Create a tensor filled with the same value using fill function

In [ ]:
t7 = torch.full((15,15) ,69)
t7

tensor([[69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69],
        [69, 69, 69,

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty. -> using cat

In [ ]:
t8 = torch.full((2,2),0.)
t9 = torch.full((2,2),1.)

# concatinating along the column
comb = torch.cat((t8,t9))

# concatinating along the row
comb = torch.cat((t8,t9),1)
comb

tensor([[0., 0., 1., 1.],
        [0., 0., 1., 1.]])

TORCH.SPLIT 

Splits the tensor into chunks. Each chunk is a view of the original tensor.

If split_size_or_sections is an integer type, then tensor will be split into equally sized chunks (if possible). Last chunk will be smaller if the tensor size along the given dimension dim is not divisible by split_size.

If split_size_or_sections is a list, then tensor will be split into len(split_size_or_sections) chunks with sizes in dim according to split_size_or_sections.

In [ ]:
a = torch.arange(10).reshape(5,2)

# with default split size:
# a =torch.split(a, 4)

# whit custom split size
# a =torch.split(a, [1,4])
# a

# splitting along the column
# a= torch.split(a,1,1)
# a[0].shape

In [ ]:
len(a)

5

##### Numpy to Tensor & Tensor to Numpy

In [ ]:
x = np.array([[1, 2], [3, 4.]])
y = torch.tensor(x)
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

Sin Function

In [ ]:
sinFunc = torch.sin(a)
sinFunc

tensor([[ 0.0000,  0.8415],
        [ 0.9093,  0.1411],
        [-0.7568, -0.9589],
        [-0.2794,  0.6570],
        [ 0.9894,  0.4121]])