In [2]:
import numpy as np
import pandas as pd
import torch

In [2]:
def model(x):
    return x @ w.t() + b

In [3]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [4]:
data = pd.read_csv('winequality-red.csv')

In [5]:
x = data['quality']

In [6]:
quality_target = np.array(x)
quality_target = quality_target

In [7]:
del data['quality']

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
dtypes: float64(11)
memory usage: 137.5 KB


In [9]:
inputs = data.to_numpy()
inputs

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [10]:
tens_inputs = torch.from_numpy(inputs)
tens_target = torch.from_numpy(quality_target)

In [11]:
print(tens_inputs)
print(tens_target)

tensor([[ 7.4000,  0.7000,  0.0000,  ...,  3.5100,  0.5600,  9.4000],
        [ 7.8000,  0.8800,  0.0000,  ...,  3.2000,  0.6800,  9.8000],
        [ 7.8000,  0.7600,  0.0400,  ...,  3.2600,  0.6500,  9.8000],
        ...,
        [ 6.3000,  0.5100,  0.1300,  ...,  3.4200,  0.7500, 11.0000],
        [ 5.9000,  0.6450,  0.1200,  ...,  3.5700,  0.7100, 10.2000],
        [ 6.0000,  0.3100,  0.4700,  ...,  3.3900,  0.6600, 11.0000]],
       dtype=torch.float64)
tensor([5., 5., 5.,  ..., 6., 5., 6.], dtype=torch.float64)


In [3]:
w = torch.randn(11, requires_grad=True)
b = torch.randn(1599, requires_grad=True)

In [13]:
b

tensor([-2.2122,  0.3696,  1.0053,  ..., -0.3548,  0.9264, -0.6025],
       requires_grad=True)

In [14]:
# preds = model(tens_inputs.float())
# preds

In [15]:
# loss = mse(preds,tens_target)
# loss

In [16]:
for i in range(7000):
    preds = model(tens_inputs.float())
    loss = mse(preds,tens_target)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-3
        w.grad.zero_()
        b.grad.zero_()

In [17]:
w

tensor([ 7.9988e-01, -1.0258e+00,  1.7449e+00, -2.7037e-01, -2.5586e-01,
         5.2178e-02, -1.9573e-04,  7.8613e-01, -1.7836e+00, -1.6895e+00,
         4.8222e-01], requires_grad=True)

In [18]:
preds = model(tens_inputs.float())
loss = mse(preds,tens_target)
print(loss)

tensor(4.3084, dtype=torch.float64, grad_fn=<DivBackward0>)


In [19]:
preds

tensor([1.1735, 4.9210, 5.2583,  ..., 3.9938, 4.4351, 3.5930],
       grad_fn=<AddBackward0>)

In [20]:
tens_target

tensor([5., 5., 5.,  ..., 6., 5., 6.], dtype=torch.float64)